### ISSUE TITLE
Issue with autoregressive_experiment.py

### ISSUE THREAD

**Issue by aflah02** [labmlai/annotated_deep_learning_paper_implementations#105]
Hey

I was trying out the code here - https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/transformers/basic/autoregressive_experiment.py
and it throws an error for Division by Zero 

```
Traceback (most recent call last):
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/labml/internal/api/__init__.py", line 97, in run
    packets = self._get_packets()
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/labml/internal/api/__init__.py", line 92, in _get_packets
    packets = [s.get_data_packet() for s in sources]
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/labml/internal/api/__init__.py", line 92, in <listcomp>
    packets = [s.get_data_packet() for s in sources]
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/labml/internal/tracker/writers/web_api.py", line 71, in get_data_packet
    self.data['track'] = self.get_and_clear_indicators()
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/labml/internal/tracker/writers/web_api.py", line 113, in get_and_clear_indicators
    step = self._mean(step, max_buffer_size)
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/labml/internal/tracker/writers/web_api.py", line 85, in _mean       
    blocks = (len(values) + n_elems - 1) // n_elems
ZeroDivisionError: integer division or modulo by zero
```

I'm not quite sure how to fix this because this seems to be in some other module file

**Comment by vpj** [comment]
The error is from, when tracking training statistics with [labml](https://github.com/labmlai/labml)

Fixed it: https://github.com/labmlai/labml/commit/cc64b94ed50edb6eb290cb61de523a10504e3240

Can you please try again? Just out of curiosity did you get this error when running on Google Colab?

**Comment by aflah02** [comment]
Thanks I'll try it again also would I need to update any thing before rerunning?
For the second part I was running it on my personal machine not Google Colab

**Comment by aflah02** [comment]
Thanks It Worked!
